name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ou la branche que vous souhaitez déclencher le déploiement

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Version de Node.js à utiliser

      - name: Install dependencies
        run: npm install  # Commande pour installer les dépendances du projet

      - name: Build
        run: npm run build  # Commande pour construire le projet (génération des fichiers statiques)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./build  # Répertoire contenant les fichiers à déployer
